/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ProofPayloadDto {
  sessionId: string
  verifierId: string
  ageThreshold: number
  statement: string
  nullifier: string
  issuedAt: string
}
export interface ProofDto {
  proofId: string
  payload: ProofPayloadDto
  signature: string
}
export interface GenerateProofInputDto {
  sessionId: string
  verifierId: string
  ageThreshold: number
  birthDate: string
  passportNumber: string
  secret: string
}
export interface VerifyProofInputDto {
  sessionId: string
  verifierId: string
  ageThreshold: number
  passportNumber: string
  proof: ProofDto
  secret: string
}
export interface VerificationResultDto {
  verified: boolean
  reason?: string
}
export declare function generateProof(input: GenerateProofInputDto): ProofDto
export declare function verifyProof(input: VerifyProofInputDto): VerificationResultDto
